# Generated by Django 5.2.1 on 2025-05-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_subject_options_subject_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['beginning_date', 'ending_date'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.RemoveField(
            model_name='section',
            name='code',
        ),
        migrations.AddField(
            model_name='section',
            name='beginning_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='ending_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
