# Generated by Django 5.2.1 on 2025-05-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_section_options_remove_section_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='schedule',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
