# Generated by Django 5.2.1 on 2025-05-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_enrollment_grade_1_alter_enrollment_grade_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
