# Generated by Django 5.2.1 on 2025-06-05 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_section_is_active'),
        ('users', '0003_remove_teacher_user_employee_delete_coordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.employee'),
        ),
    ]
